// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookStoreWebApi.Models
{
    public partial class GetBooksSortedByAuthorTitleResult
    {
        public int Id { get; set; }
        public string Publisher { get; set; }
        public string Title { get; set; }
        public string Author_LastName { get; set; }
        public string Author_FirstName { get; set; }
        [Column("Price", TypeName = "decimal(18,0)")]
        public decimal Price { get; set; }
    }
}
