// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BookStoreWebApi.Models
{
    public partial class GetTotalPriceResult
    {
        [Column("TotalPrice", TypeName = "decimal(38,0)")]
        public decimal? TotalPrice { get; set; }
    }
}
