// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BookStoreWebApi.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BookStoreWebApi.Models
{
    public partial interface ImasterContextProcedures
    {
        Task<List<GetBooksSortedByAuthorTitleResult>> GetBooksSortedByAuthorTitleAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetBooksSortedByPublisherAuthorTitleResult>> GetBooksSortedByPublisherAuthorTitleAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetTotalPriceResult>> GetTotalPriceAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
